# ---- SERVER ----
server.port=8080

# ---- EUREKA ----
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ---- GATEWAY DISCOVERY ----
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ---- ROUTES ----
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/orders/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[0].id=cart-service
spring.cloud.gateway.routes[0].uri=lb://CART-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/cart/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[0].id=inventory-service
spring.cloud.gateway.routes[0].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/inventory/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[0].id=payment-service
spring.cloud.gateway.routes[0].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/payments/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[0].id=review-service
spring.cloud.gateway.routes[0].uri=lb://REVIEW-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/reviews/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://product-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/products/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# ---- ACTUATOR ----
management.endpoints.web.exposure.include=health,info,refresh
